(() => {
  const section = document.createElement('section');
  section.id = 'case-studies';
  section.className = 'section shell';
  section.innerHTML = `<div class="section-heading"><div><p class="eyebrow">Inside the work</p><h2>Decisions that make a product credible.</h2></div><p>Founder-led product architecture, concrete demonstrations, and the next evidence each system needs.</p></div><div class="work-grid">
    <article class="work-card"><div class="work-label">Research & intelligence</div><h3>Macro Indicator Studio</h3><p><strong>Problem:</strong> Research spans fragmented sources, methods, and data histories.</p><p><strong>Contribution:</strong> Product and architecture work connecting indicator exploration, ingestion, analysis, provenance, and an AI research copilot.</p><p><strong>Decision:</strong> Keep deterministic analysis and source lineage visible alongside AI assistance.</p><p><strong>Demonstration:</strong> A public research workspace with documented connector and security improvements.</p><p><strong>Next proof:</strong> Independent validation of outputs, source coverage, and sustained user value.</p><a class="card-link" href="https://v-macro-indicator-studio-1.onrender.com/" target="_blank" rel="noreferrer">Inspect the workspace ↗</a></article>
    <article class="work-card"><div class="work-label">Enawuga · institutional side</div><h3>Model6</h3><p><strong>Problem:</strong> Institutional finance needs an inspectable demonstration before real integration.</p><p><strong>Contribution:</strong> Institutional backend architecture, cleaned source baseline, and public investor replay.</p><p><strong>Decision:</strong> Separate fictional replay from controlled adapters and future institutional connections.</p><p><strong>Demonstration:</strong> Fictional bank/MFI transaction, liquidity, reconciliation, lending, and portfolio scenarios.</p><p><strong>Next proof:</strong> Authenticated lab integration evidence. Public replay does not prove live settlement.</p><a class="card-link" href="https://model6-demo.onrender.com/" target="_blank" rel="noreferrer">Inspect the institutional replay ↗</a></article>
    <article class="work-card"><div class="work-label">Enawuga · field side</div><h3>Sovereign Core</h3><p><strong>Problem:</strong> Rural-finance concepts must make actor context, actions, and resulting evidence understandable.</p><p><strong>Contribution:</strong> Product journey and controlled architecture connecting Agent, Farmer, Pump, PAYG, Receipt, and Audit.</p><p><strong>Decision:</strong> One synthetic world with role scope, tenant denials, explicit simulations, and deterministic reset.</p><p><strong>Demonstration:</strong> A simulated action changes receipt state and produces causal audit evidence; reset restores baseline.</p><p><strong>Next proof:</strong> Reviewer evidence and separately authorized integration contracts.</p><a class="card-link" href="https://sovereign-core-five.vercel.app/static/index.html" target="_blank" rel="noreferrer">Follow the pilot journey ↗</a></article>
  </div>`;
  document.querySelector('#work').after(section);
})();
